name: CI/CD Deploy - EJKEVIN

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front_despacho
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/DevOpsEV2Frontend:latest
          build-args: |
            VITE_API_DESPACHO=${{ secrets.VITE_API_DESPACHO }}
            VITE_API_VENTAS=${{ secrets.VITE_API_VENTAS }}

      - name: Deploy en EC2 Frontend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_FRONT }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/DevOpsEV2Frontend
            git pull origin deploy
            cat > .env <<EOF
            IP_VENTAS=${{ secrets.IP_PRIVADA_EC2_VENTAS }}
            IP_DESPACHOS=${{ secrets.IP_PRIVADA_EC2_DESPACHOS }}
            EOF
            docker-compose pull frontend
            docker-compose up -d frontend